[package]
name = "kadouchi"
version = "0.1.0"
authors = ["Pyry Kontio <pyry.kontio@drasa.eu>"]

[dependencies]
regex = "1.0"
nom = "4.0"
scoped_stack = { git = "https://github.com/golddranks/scoped_stack" }
failure = "0.1"
libloading = "0.5"
log = "0.4"
env_logger = "0.5"